name: build

on:
  push:
    branches:
    - '**'
  workflow_dispatch:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.6.7', '9.8.4', '9.12.2', '9.14.1']

    env:
      CONFIG: "--enable-tests --enable-benchmarks"

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup
      name: Setup Haskell tools
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: false

    - name: Test source distribution
      run: |
        cabal sdist
        mkdir test_dir
        cd test_dir
        tar xf ../dist-newstyle/sdist/blst-clib-0.3.16.tar.gz
        cd blst-clib-0.3.16
        cabal test
